### ISSUE TITLE
Radex RD1212v1 - set time on device

### ISSUE THREAD

**Issue by ZeroChaos-** [luigifab/python-radexreader#11]
I'm using the radex 1212v1 bus powered for my testing.  When I have to unplug/plug, it doesn't hold time very well.  It's much worse when I unplug it for a little while.  it would be great to be able to automatically push the time to the device so it's accurate.

**Comment by luigifab** [comment]
Is it possible with the software of the manufacturer?

**Comment by ZeroChaos-** [comment]
I have only tested the android software, and no, it doesn't.  This feature request is entirely wishful thinking.  If the windows software doesn't support it either then feel free to close it.
