### ISSUE TITLE
error on MacOS Python3

### ISSUE THREAD

**Issue by GuzzoTheLuke** [luigifab/python-radexreader#12]
Hi, when I run the program (radexreader.py) with "readall" command I receive this message
`Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    readall
NameError: name 'readall' is not defined`

When I use "radexreader readall" command I receive this other message
`SyntaxError: invalid syntax`

Where am I doing wrong? 
Thanks for the help!

**Comment by luigifab** [comment]
How did you install the program? How do you run the program?
What is your Python version?

**Comment by GuzzoTheLuke** [comment]
I'm trying to run the Python program via IDLE on my mac with Python 3 installed. 
sorry but i'm not very familiar with Python, I hope I haven't misconstrued Python

![Schermata 2022-12-03 alle 15 31 07](https://user-images.githubusercontent.com/97561258/205446081-6deff92c-ebe7-4b67-9a4f-cf8e826c05ae.png)

**Comment by luigifab** [comment]
Okay, no, you must run the program like any other program from a Terminal.
For example:
![image](https://user-images.githubusercontent.com/31816829/205447263-ff619cc0-be94-4f64-b094-2b4e32b3bb15.png)

Edit: perhaps with IDLE you can do the same by typing `/Users/..../radexreader.py` and `readall` on the same line.

**Comment by GuzzoTheLuke** [comment]
![Schermata 2022-12-03 alle 16 15 32](https://user-images.githubusercontent.com/97561258/205448156-01bed9fe-5932-405e-98e1-6ec708b26643.png)
The result is not better :'(

**Comment by GuzzoTheLuke** [comment]
![Schermata 2022-12-03 alle 16 19 10](https://user-images.githubusercontent.com/97561258/205448272-f8184b27-0227-4dd3-ba22-7d83bc43deb6.png)
refering to "edit"

**Comment by luigifab** [comment]
Good. Now you need to install `libusb`, for example: `brew install libusb`.

**Comment by GuzzoTheLuke** [comment]
same result `zsh: command not found: readall`

**Comment by luigifab** [comment]
**No YOU MUST write the command line in one line!**

**Comment by GuzzoTheLuke** [comment]
![Schermata 2022-12-03 alle 19 27 45](https://user-images.githubusercontent.com/97561258/205456197-949d005a-e3f5-4aca-a7d5-bb29fb85ef33.png)
I'm really sorry, but I can't understand what I'm doing wrong...  😭

**Comment by GuzzoTheLuke** [comment]
Sorry, do you have some hints about the problem?

**Comment by luigifab** [comment]
It's seems that `libusb` is not installed? or perhaps you need to use `sudo`?
`sudo python3 ....`

**Comment by GuzzoTheLuke** [comment]
`pip install pyusb`
`Requirement already satisfied: pyusb in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (1.2.1)`

and `sudo` don't change anything

**Comment by luigifab** [comment]
Yes, the problem is not `pyusb`  but `libusb`.

With Windows you need to download a .dll and put it in the right directory.
With Alpine Linux you need to run `apk add libusb`.
With Mac I'm not sure, something like `brew install libusb` ([source](https://stackoverflow.com/questions/3853634/how-to-set-up-libusb-on-mac-os-x)).

**Comment by GuzzoTheLuke** [comment]
> ![Schermata 2022-12-03 alle 19 27 45](https://user-images.githubusercontent.com/97561258/205456197-949d005a-e3f5-4aca-a7d5-bb29fb85ef33.png) I'm really sorry, but I can't understand what I'm doing wrong... 😭

Sorry I give up... I've done what you were asking, I tried to reinstall libusb and pyusb (the error change when I tried compiling with one of those installed) and I've checked that Python3 was up to date... I don't know what to do...
You've tried to help, but your suggestion can't help me.
Good luck

**Comment by luigifab** [comment]
I think the problem is not python, but only **libusb**.
But I don't know how to help you.
