### ISSUE TITLE
Radex RD1212v1 - Read data in realtime

### ISSUE THREAD

**Issue by Thempra** [luigifab/python-radexreader#4]
(Device Radex 1212 without BT)
Setup like official doc: https://quartarad.com/rd1212-software-radexread/

I tried with all commands (tail, readlast, jsonlast, .... ) but never refresh data.

It would be a great feature (realtime) to process json data by other monitor apps.

**Comment by luigifab** [comment]
To work, you must configure your Radex to save measures.
Go to *Menu*, *Data collection*, check *On*, and set *Recording period* to 1 minute, and save.
Wait 1 minute and re run the tail command.

If it doesn't work, perhaps you can test the init.py provided in #3.

**Comment by luigifab** [comment]
To work, you must configure your Radex to save measures.
Go to *Menu*, *Data collection*, check *On*, and set *Recording period* to 1 minute, and save (like the official doc, but my device never display Connected to PC, only USB).

Wait 1 minute and re run the tail command:

![image](https://user-images.githubusercontent.com/31816829/110971748-89acd500-835b-11eb-9a07-59862fb0fee8.png)

If it doesn't work, perhaps you can test the init.py provided in #3.

**Comment by Thempra** [comment]
Maybe it's a firmware/hardware question .... I have Version 1.1 (Menu / Service)

**Comment by luigifab** [comment]
EDIT: oh sorry, I understand you 15 days after... if the tail command never update for you, I don't know, have you "real-time" with original software (radexread)? or are you forced to disconnect the device to get new measures?

**Comment by Thempra** [comment]
Yes, I tried it and same results, read ok, but no read in realtime. I will contact with radex support to upgrade device firmware.

Thx !!
