### ISSUE TITLE
[pydroid3] usb.core.NoBackendError: No backend available

### ISSUE THREAD

**Issue by Tobbinloggin** [luigifab/python-radexreader#6]
I'm attempting to run this code on Android to see if it's possible, I downloaded Pydroid3(it's an android app), and attempted to run the code, I got a `no backend available` error, I copied libusb-1.0.dll into the app's folder (which was one of the folders that appeared when I checked $PATH)

![ls](https://user-images.githubusercontent.com/53196506/114327278-e997c680-9b27-11eb-8a38-e21fc37d9ace.png)

It worked, but the no backend error still occurred.

![nobackend](https://user-images.githubusercontent.com/53196506/114327313-0207e100-9b28-11eb-84e9-4d7df6f7fd6b.png)

Do you have any idea how to implement this code on an Android phone?

**Comment by Tobbinloggin** [comment]
I tried disabling Libusb and using serial mode instead, that didn't work, serial isn't compatible with Android, the geiger counter didn't show up when I plugged it in.

![Screenshot_20210411-204758_Pydroid 3](https://user-images.githubusercontent.com/53196506/114327509-e4874700-9b28-11eb-99b9-f1c13dff82a8.jpg)

With USBSerial4a I can see the device, I don't know how to implement this Android compatible code though, not enough experience with Python.

https://github.com/jacklinquan/usbserial4a

Not that it stopped me from trying (and failing).

![Pytool](https://user-images.githubusercontent.com/53196506/114327212-a63d5800-9b27-11eb-80e7-e0c644c8fbb2.png)

**Comment by luigifab** [comment]
You can't copy libusb-1.0.dll into Android, you need libusb for Android, or anything else.
For the Radex RD1212, the Silicon labs  is an UART bridge, it provide a serial port.

If with USBSerial4a you can see the device, you must modify my python program to import USBSerial4a.
See USBSerial4a examples (I tried to add [some code](https://gist.github.com/luigifab/00b1df83688d5c167ce742e189113851)).

**Comment by Tobbinloggin** [comment]
I still get the no backend error.

If you can get this to work on a phone I'd use it everyday, that's what I'm planning with this device, I want a personal dosimeter, I want to record daily logs and save them long term, that way I can notice high radiation areas(if there are any) and avoid those areas.

**Comment by Tobbinloggin** [comment]
You'll be my hero if you figure out a way to constantly log data onto my phone with the Radex One.

**Comment by luigifab** [comment]
You can retry the [gist](https://gist.github.com/luigifab/00b1df83688d5c167ce742e189113851) (I have enabled some code for android).
But I don't know if it's a good start or not.

**Comment by Tobbinloggin** [comment]
`No module named 'usb'`

**Comment by luigifab** [comment]
Try to comment lines 24/25/26.
